# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20160430_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_mame',
            new_name='student_name',
        ),
    ]
