# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20160430_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_username',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='team_data',
            field=models.CharField(default=' ', max_length=5000),
        ),
    ]
