# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20160430_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_about',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='team_briefinfo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
