# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_update',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_data',
            field=models.CharField(default=' ', max_length=10000),
        ),
    ]
